### PR TITLE
Add pagination

### PR DESCRIPTION
**Pull request by edwinfelipe**

### CODE REVIEW

**Comment by edwinfelipe** [comment]
issue #99 solved with all the criteries

**Comment by edwinfelipe** [comment]
sorry for aditional commits, I think it was a problem with my fork

**Comment by edwinfelipe** [comment]
@iamdarshshah can you tell me the specific styles you need, I only let the default styles, I will work on it on the next weekend or maybe tomorrow

**Comment by edwinfelipe** [comment]
Ok, I will do it today

**Comment by edwinfelipe** [comment]
I add the required changes, and create a new component for pagination to separate it from the Content component

**Comment by iamdarshshah** [comment]
@edwinfelipe This looks great! It needs a couple of changes:
- [ ] the text and arrow `next ->` is not aligned properly. Please update the changes.
- [ ] Once we search for something, then the index values for the pagination should get updated, Ex. if we search and the search result is just one element then too in the current scenario we'll able to see `Page 1 of 11`, also with that we are able to do `next` `prev` calls, which should not be the case. Instead, if we search let's say there are a total of 12 elements, then as per calculation we should just see `Page 1of 2`.

I hope this makes sense and if you have any queries regarding this then let me know.

Otherwise, LGTM!

**Comment by edwinfelipe** [comment]
I can't see the align problem, please send me a picture

**Comment by iamdarshshah** [comment]
@edwinfelipe Now, the search functionality works as expected with pagination but there arises one more scenario where it fails.
Let's say we are searching for a username starting with `D` and then it shows `Page 1 of 6`, This is working as expected but if i remove `D` from the search field i.e., we have removed our searchTerm, then it should show `Page 1 of {Total pages i.e., 11 for now}` but it still shows `Page 1 of 6`. 

Screenshot for the alignment issue:
Screenshot (57)

> arrow should be vertically aligned with the text.

I hope this makes sense and if you have any queries regarding this then let me know.

**Comment by edwinfelipe** [comment]
Now it is solved, sorry I am not so focused on details XD

**Comment by iamdarshshah** [comment]
> Now it is solved, sorry I am not so focused on details XD

No problem! This looks good now. Can you please add some more changes to it:
- [ ] on hover to next or prev the `cursor-pointer: pointer`
- [ ] This is what happens when we click on `next` or `prev` while we have `dark-theme`.
Screenshot (59)
> This should not happen. Please update it.

Otherwise, after these changes, Will merge this PR. Thanks @edwinfelipe

**Comment by edwinfelipe** [comment]
all ready

**Review by iamdarshshah — APPROVED** [review]
LGTM! Thanks @edwinfelipe :+1:

**Comment by iamdarshshah** [comment]
Fixes #132 :tada:

**Comment by iamdarshshah** [comment]
Fixes #99 :tada:

**Pull request merged**
