### PR TITLE
Ashyum.json

### PR DESCRIPTION
**Pull request by Ashyum**
Added about myself in src/contributors folder.

### CODE REVIEW

**Review by iamdarshshah — APPROVED** [review]
LGTM! Thanks @Ashyum

**Comment by Ashyum** [comment]
Thanks @iamdarshshah . I am new to oen source.

**Comment by Ashyum** [comment]
Thank you @iamdarshshah. I am new to open source.

**Comment by iamdarshshah** [comment]
Hey, @Ashyum It's great to see you have taken your first step towards Open-Source! Keep it up 👍

**Pull request merged**
