### PR TITLE
Fix Frej's file encoding

### LINKED ISSUE #116: Fix characters (Å, Ä, Ö, Ø and so on)
**Is your feature request related to a problem? Please describe.**
The website won't show Scandinavian characters like Å, Ä and Ö.

**Describe the solution you'd like**
More supported characters.

**Describe alternatives you've considered**
Add UTF-8 or something that supports more characters.

**Additional context**
My full name won't display properly on the website (Frej Björnsson)

### PR DESCRIPTION
**Pull request by tamtamchik**
Closes #116

### CODE REVIEW

**Comment by iamdarshshah** [comment]
Hey, @tamtamchik Thanks for updating it. Are you sure it's just because of white-space? What can be the issue and is there any workaround using which we might not face this issue in the future?

**Comment by FrejBjornsson** [comment]
The characters are still wrong. I don't really know how to fix it. Can you add an external file that encodes all text into UTF-8 for the website..? Or maybe there's an easier fix.

**Comment by iamdarshshah** [comment]
@FrejBjornsson You can find deploy preview for this PR - https://deploy-preview-121--hacktoberfest-participants.netlify.app

**Comment by tamtamchik** [comment]
@iamdarshshah the problem was in the file encoding, it was not UTF-8, but some ISO XXX (can't remember already).
Whitespaces are just a side effect. All I did – force the file encoding to be UTF-8 with Sublime Text editor.

I can't recall any modern developer toolset that does not use UTF-8 as default (btw, @FrejBjornsson what editor you use?)
Using [iconv](https://en.wikipedia.org/wiki/Iconv) somewhere inside the codebase to force encoding to be UTF-8, is overkill for this project (IMHO)

**Comment by FrejBjornsson** [comment]
@tamtamchik 

I use Visual Studio.

**Comment by tamtamchik** [comment]
@FrejBjornsson if it's not Visual Studio **Code** this could be a reason. VS, afaik, uses Windows code pages to auto-determine file encoding, e.g. if you have Cyrillic symbols in the file it'll save it most probably in Windows-1251 codepage.

**Comment by FrejBjornsson** [comment]
@tamtamchik Ok weird that it didn't work for me. Will check my developer environment. Do you recommend VS Code?

**Comment by tamtamchik** [comment]
@FrejBjornsson yep, for JS/Node development it's great. 
You can also test out [Atom](https://atom.io). 
I personally use WebStorm.

**Comment by FrejBjornsson** [comment]
Ok will check them out. Thanks for all the help 😊

**Comment by iamdarshshah** [comment]
@tamtamchik  It makes sense. Thanks for pointing this out. Will need to explore a bit about this issue later today. But for now, merging this PR. 👍

**Comment by iamdarshshah** [comment]
FIxes #116 🎉

**Pull request merged**
